import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useState } from 'react';
import Game from '../components/Game';
import Header from '../components/Header';
import { GameSelections } from '../components/types';

const initialGameState = {
  user1: null,
  user2: null,
  winState: null
};

const Home: NextPage = () => {
  const [score, setScore] = useState(0);
  const [gameState, setGameState] = useState<GameSelections>(initialGameState);
  const [reveal, setReveal] = useState(false);

  function playAgain() {
    setGameState(initialGameState);
    setReveal(true);
  }

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="radialBgDiv"></div>
      <main className="mx-auto max-w-5xl p-12">
        <Header reveal={reveal} score={score} />
        <Game
          setReveal={setReveal}
          playAgain={playAgain}
          gameState={gameState}
          setGameState={setGameState}
          setScore={setScore}
        />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
